# Generated by Django 3.2.11 on 2022-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='original_url',
            field=models.URLField(max_length=5000),
        ),
    ]
